apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: training-portal
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/health-probe-path: /
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: training.sneakertail.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
